### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by bloodclot** [arturino009/POEcluster#6]
Hey thanks for the change to Panda, it's really clean. I ended up needing to install Panda and PandaGUI as dependencies also. I am, however, running into a problem. Seems to affect the old TKtree version as well. Any ideas what this could be? I tried messing around with priceGetter to fix this but I'm not very experienced and couldn't figure it out. Thank you!

```
C:\E\poe\tools\POEcluster-master new>PoeCluster.py
Traceback (most recent call last):
  File "C:\E\poe\tools\POEcluster-master new\PoeCluster.py", line 2, in <module>
    import priceGetter
  File "C:\E\poe\tools\POEcluster-master new\priceGetter.py", line 316, in <module>
    current_league = getLeague()
  File "C:\E\poe\tools\POEcluster-master new\priceGetter.py", line 11, in getLeague
    leagues = leagues.json()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by arturino009** [comment]
I changed the description to list all required dependencies.

**Comment by arturino009** [comment]
As for the error, it's probably fixed now, as POE servers just weren't responding to requests without a user-agent, so it was added. But now requests are extremely slow. We are talking 1 request every 5 seconds. I can't really do anything about this, as POE servers are overloaded currently.
