### ISSUE TITLE
Problem on my end or is the requested json file empty ?

### ISSUE THREAD

**Issue by Arecurius0** [arturino009/POEcluster#7]
```
$ python PoeCluster.py
Input 1 for single notable prices, 2 for double notable prices.
1
Input 1 to check small cluster jewels, 2 for medium cluster jewels.
1
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "PoeCluster.py", line 48, in <module>
    all_lists = json.load(json_file)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PoeCluster.py", line 93, in <module>
    stop = int(input())
ValueError: invalid literal for int() with base 10: ''

```

**Comment by arturino009** [comment]
Are you using the latest version of the tool? Some things were changed recently, so all data should be requested. I also recommend deleting the 'data' folder, because I think there isn't any logic for rechecking if the downloaded files are correct.

**Comment by Arecurius0** [comment]
i set everything up just yesterday fresh from here. After deleting the data folder i tried executing again and got this message:


```
$ python PoeCluster.py
Didn't find data for current league. Updating...
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
1
```
i thought i had all dependencies. maybe not... but after entering 1 as an answer to the question it didnt seem anything more was happening. Script exited and that was it

**Comment by Arecurius0** [comment]
resolving the dependency issue with 
pip install lxml
resolved the treebuilding issue.

Im currently looking at this:

```
$ python PoeCluster.py
Didn't find data for current league. Updating...
Input 1 for single notable prices, 2 for double notable prices.
2
```

edit: ok terminal has been like this for >5minutes now. i dont think anything is happening anymore

**Comment by Arecurius0** [comment]
After stopping the process with ctrl+c i got alot of output into my terminal

```
Base: +4% to Fire Damage over Time Multiplier
ilvl: 1
Listings:2072
Average median price: 4.94

Base: +4% to Fire Damage over Time Multiplier
ilvl: 50
Listings:2013
Average median price: 4.94

Base: +4% to Fire Damage over Time Multiplier
ilvl: 68
Listings:1852
Average median price: 4.94

Base: +4% to Fire Damage over Time Multiplier
ilvl: 75
Listings:1088
Average median price: 6.0

Not enough items!(1) Skipping...

Not enough items!(6) Skipping...

Not enough items!(1) Skipping...

Eye of the Storm and Blowback: 0.069% Cost for rerolls: 541.34 Tries: 1452
Listings:10
Price:  30   chaos

Price:  40   chaos

Price:  40   chaos

Price:  45   chaos

Price:  45   chaos

Price:  50   chaos

Price:  82.48   chaos

Price:  82.48   chaos

Price:  82.48   chaos

Price:  164.96   chaos

The average median is  49.5      Profit: -496.78

Not enough items!(2) Skipping...

Not enough items!(7) Skipping...

Eye of the Storm and Burning Bright: 0.069% Cost for rerolls: 541.34 Tries: 1452
Listings:12
Price:  40   chaos

Price:  40   chaos

Price:  41   chaos

Price:  50   chaos

Price:  50   chaos

Price:  60   chaos

Price:  90   chaos

Price:  82.48   chaos

Price:  82.48   chaos

Price:  82.48   chaos

The average median is  59.5      Profit: -486.78

Not enough items!(5) Skipping...

Not enough items!(4) Skipping...

Eye of the Storm and Haemorrhage: 0.069% Cost for rerolls: 541.34 Tries: 1452
Listings:33
Price:  1   chaos

Price:  5   chaos

Price:  7   chaos

Price:  7   chaos

Price:  8   chaos

Price:  8   chaos

Price:  10   chaos

Price:  10   chaos

Price:  10   chaos

Price:  10   chaos

The average median is  8.0      Profit: -538.28

Not enough items!(8) Skipping...

Eye of the Storm and Exposure Therapy: 0.139% Cost for rerolls: 298.9 Tries: 720
Listings:12
Price:  20   chaos

Price:  25   chaos

Price:  25   chaos

Price:  30   chaos

Price:  35   chaos

Price:  40   chaos

Price:  40   chaos

Price:  40   chaos

Price:  45   chaos

Price:  50   chaos

The average median is  39.5      Profit: -264.34

Not enough items!(5) Skipping...

Eye of the Storm and Vile Reinvigoration: 0.069% Cost for rerolls: 541.34 Tries: 1452
Listings:10
Price:  22   chaos

Price:  40   chaos

Price:  44   chaos

Price:  50   chaos

Price:  55   chaos

Price:  60   chaos

Price:  75   chaos

Price:  82.48   chaos

Price:  123.72   chaos

Price:  164.96   chaos

The average median is  59.5      Profit: -486.78

Not enough items!(7) Skipping...

Eye of the Storm and Brewed for Potency: 0.139% Cost for rerolls: 298.9 Tries: 720
Listings:13
Price:  10   chaos

Price:  15   chaos

Price:  20   chaos

Price:  25   chaos

Price:  40   chaos

Price:  40   chaos

Price:  40   chaos

Price:  40   chaos

Price:  40   chaos

Price:  40   chaos

The average median is  39.67      Profit: -264.18

Not enough items!(9) Skipping...

Not enough items!(2) Skipping...

Not enough items!(4) Skipping...

Not enough items!(3) Skipping...

Not enough items!(0) Skipping...

Not enough items!(1) Skipping...

Not enough items!(2) Skipping...

Not enough items!(2) Skipping...

Not enough items!(0) Skipping...

Not enough items!(2) Skipping...

Rate limit exceeded
Rate limit exceeded
Rate limit exceeded
Rate limit exceeded
Traceback (most recent call last):
  File "PoeCluster.py", line 81, in <module>
    notableData = priceGetter.getNotablePrice(a, b, query, inp, jewel_price)
  File "C:\Spiele\Poe extras\POEcluster-master\priceGetter.py", line 193, in getNotablePrice
    time.sleep(60)
KeyboardInterrupt
```

**Comment by Arecurius0** [comment]
seems like its not able to finish in a reasonable amount of time due to being rate limit by GGG request api.

**Comment by Arecurius0** [comment]
i tried letting the program run for like an hour or so and now my trade requests per browser are depleted "rate limit exceeded" yikes hopefully i can use trade normally soon again

**Comment by arturino009** [comment]
Yeah. I added lxml to the dependency list. I forgot about it.
Rate limit resets after some time. I'm not really sure what time, I think about a minute or two for me.
About the time of execution... It kinda sucks. Especially the double notable requesting. Before it took about 15 minutes to get all double notable prices (when the delay for requests was 0.4 seconds). Now the delay is 5 seconds, and you still get rate limited. That means it would take about 150 minutes at least to get all prices for double notables. There is nothing I can do about this right now. We are requesting thousands of notable combinations after all.

**Comment by arturino009** [comment]
Well, now I updated the delay, so it should't be rate limited anymore.
