### ISSUE TITLE
Didn't find data for current league. Updating...

### ISSUE THREAD

**Issue by AlphaCaster** [arturino009/POEcluster#9]
Hi @Artuino009,

Not sure if you're still supporting this, I noticed the update for 3.15 and decided to give it a shot.
When I run the program it tries to update the data for the new league but throws an error in updateCLusterData.py line 53, line 53, in get_data_poedb
    for i in allStats['result'][4]['entries'][1]['option']['options']:
KeyError: 'option'

```
Didn't find data for current league. Updating...
'option'

Traceback (most recent call last):
  File "C:\Users\kypes\Desktop\POEcluster-master\PoeCluster.py", line 32, in <module>
    updateClusterData()
  File "C:\Users\kypes\Desktop\POEcluster-master\updateClusterData.py", line 93, in updateClusterData
    json.dump(get_data_poedb("Small"), outfile)
  File "C:\Users\kypes\Desktop\POEcluster-master\updateClusterData.py", line 53, in get_data_poedb
    for i in allStats['result'][4]['entries'][1]['option']['options']:
KeyError: 'option'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kypes\Desktop\POEcluster-master\PoeCluster.py", line 105, in <module>
    stop = int(input())
ValueError: invalid literal for int() with base 10: ''
>>> 
```

I've tried looking at the other revisions to see if I could solve the problem but I've been unsuccessful.
Thanks!

**Comment by arturino009** [comment]
You can try downloading the repo again, I fixed the issue (change 1 to 0). Don't forget to delete the 'data' folder as well.
